name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
      - name: Install modules
        run: npm install
      - name: Copy configuration
        run: cp exampleconfig.json config.json
      - name: Run ESLint
        run: npx eslint . --ext .ts
      - name: Compile Typescript
        run: npm run build
